"""Render the evidence files the report cites. Output is deterministic: same inputs, same bytes."""

from __future__ import annotations

from collections import Counter

from . import plan, runbook
from .checks import render
from .model import Migration
from .plan import HEADROOM

HEADER = [
    "> Fictional sample data (Harbor Goods). Generated by `scripts/build_evidence.py` from `data/synthetic/`,",
    "> `plan/` and `migration/dms/`. Do not edit; run `make evidence`.",
]


def _table(headers: list[str], rows: list[list[object]]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return lines


def _doc(title: str, *blocks: list[str]) -> str:
    lines = [f"# {title}", "", *HEADER, ""]
    for block in blocks:
        lines += [*block, ""]
    return "\n".join(lines).rstrip() + "\n"


def inventory(m: Migration) -> str:
    servers = sorted(m.servers.values(), key=lambda s: s["server_id"])
    outside = {d[end] for d in m.dependencies for end in ("consumer", "provider") if d[end].startswith("EXT-")}
    totals = [
        f"- Servers: {len(servers)} across {len(m.applications)} applications.",
        f"- Capacity: {sum(int(s['vcpu']) for s in servers)} vCPU, {sum(int(s['ram_gb']) for s in servers)} GB RAM,"
        f" {sum(int(s['disk_gb']) for s in servers)} GB disk.",
        f"- Database: PostgreSQL {m.migrated_schemas()[0]['version']}, "
        f"{sum(float(r['size_gb']) for r in m.migrated_schemas()):.1f} GB in {len(m.migrated_schemas())} schemas, "
        f"{sum(int(r['tables']) for r in m.migrated_schemas())} tables.",
        f"- Dependencies: {len(m.dependencies)} connections, {len(outside)} outside parties"
        f" ({', '.join(sorted(outside))}).",
        f"- Scheduled jobs: {len(m.jobs)}; public or internal DNS names: {len(m.dns_records)}.",
    ]
    rows = [
        [
            s["server_id"],
            s["hostname"],
            s["app_id"],
            s["software"],
            s["vcpu"],
            s["ram_gb"],
            f"{s['cpu_p95_pct']}%",
            f"{s['mem_p95_pct']}%",
        ]
        for s in servers
    ]
    return _doc(
        "E-01 Discovery inventory summary",
        totals,
        _table(["Server", "Host", "App", "Software", "vCPU", "RAM GB", "CPU p95", "Mem p95"], rows),
    )


def classification(m: Migration) -> str:
    counts = Counter(entry["strategy"] for entry in m.classification.values())
    summary = [f"- {strategy}: {counts[strategy]}" for strategy in sorted(counts)]
    rows = []
    for sid in sorted(m.servers):
        entry = m.classification[sid]
        wave = m.wave_of(sid)
        rows.append(
            [sid, m.servers[sid]["hostname"], entry["strategy"], "retained" if wave is None else wave, entry["target"]]
        )
    return _doc(
        "E-02 7R classification and waves", summary, _table(["Server", "Host", "Strategy", "Wave", "Target"], rows)
    )


def dependencies(m: Migration) -> str:
    blocks = []
    for after in range(0, m.max_wave + 1):
        label = "Before migration" if after == 0 else f"After wave {after}"
        rows = []
        for dep in m.dependencies:
            if dep["consumer"].startswith("EXT-") or dep["provider"].startswith("EXT-"):
                continue
            provider = m.provider_after(dep["consumer"], dep["provider"], after)
            a, b = m.location(dep["consumer"], after), m.location(provider, after)
            if "gone" in (a, b):
                continue
            hybrid = "yes" if {a, b} == {"onprem", "aws"} else "no"
            rows.append([dep["consumer"], a, provider, b, dep["port"], hybrid])
        blocks.append(
            [f"## {label}", "", *_table(["Consumer", "Runs in", "Provider", "Runs in", "Port", "Over VPN"], rows)]
        )
    links = sorted(m.hybrid_links(), key=str)
    link_rows = [[c, p, port, f, "open" if u is None else u] for c, p, port, f, u in links]
    blocks.append(
        ["## Hybrid links", "", *_table(["Consumer", "Provider", "Port", "From wave", "Until wave"], link_rows)]
    )
    return _doc("E-03 Dependencies by wave", *blocks)


def sizing(m: Migration) -> str:
    rows = []
    for name, svc in sorted(m.target["services"].items()):
        for sid in svc["sources"]:
            s = m.servers[sid]
            need_cpu = float(s["vcpu"]) * float(s["cpu_p95_pct"]) / 100 * HEADROOM
            need_mem = float(s["ram_gb"]) * float(s["mem_p95_pct"]) / 100 * HEADROOM
            rows.append(
                [
                    f"ECS {name}",
                    sid,
                    f"{need_cpu:.2f} vCPU",
                    f"{svc['cpu'] / 1024:g} vCPU",
                    f"{need_mem:.2f} GB",
                    f"{svc['memory'] / 1024:g} GB",
                ]
            )
    db = m.target["database"]
    s = m.servers[db["source"]]
    rows.append(
        [
            f"RDS {db['instance_class']}",
            db["source"],
            f"{float(s['vcpu']) * float(s['cpu_p95_pct']) / 100 * HEADROOM:.2f} vCPU",
            f"{db['instance_vcpu']} vCPU",
            f"{float(s['ram_gb']) * float(s['mem_p95_pct']) / 100:.2f} GB",
            f"{db['instance_memory_gb']} GB",
        ]
    )
    size = sum(float(r["size_gb"]) for r in m.migrated_schemas())
    notes = [
        f"- Rule: target >= source size x p95 use x {HEADROOM}. RDS memory has no headroom: its p95 is page cache.",
        f"- Storage: {db['allocated_storage_gb']} GB allocated for {size:.1f} GB of data (>= 2x), autoscaling to"
        f" {db['max_allocated_storage_gb']} GB.",
        f"- Engine: PostgreSQL {m.migrated_schemas()[0]['version']} on premises to {db['engine_version']} on RDS.",
    ]
    return _doc(
        "E-04 Target sizing",
        notes,
        _table(["Target", "Source", "CPU needed", "CPU given", "Memory needed", "Memory given"], rows),
    )


def dms_coverage(m: Migration) -> str:
    rows = []
    for row in m.migrated_schemas():
        excluded = [t for t in m.tables_without_pk() if t.startswith(row["schema"] + ".")]
        rows.append(
            [
                row["schema"],
                row["tables"],
                row["size_gb"],
                row["max_lob_kb"],
                row["change_rate_mb_per_hour"],
                ", ".join(excluded) or "none",
            ]
        )
    tasks = m.data_migration["tasks"]
    notes = [
        f"- Forward task `{tasks['forward']['id']}`: {tasks['forward']['migration_type']}.",
        f"- Reverse task `{tasks['reverse']['id']}`: {tasks['reverse']['migration_type']}.",
        f"- Tables the forward task must load: {m.expected_table_count()} (go/no-go criterion G-01).",
        f"- LOB limit: {m.forward_settings['TargetMetadata']['LobMaxSize']} KB; largest LOB in the inventory:"
        f" {max(int(r['max_lob_kb']) for r in m.migrated_schemas())} KB.",
        f"- Combined change rate: {sum(float(r['change_rate_mb_per_hour']) for r in m.migrated_schemas()):.0f}"
        " MB per hour.",
    ]
    return _doc(
        "E-05 DMS coverage",
        notes,
        _table(["Schema", "Tables", "Size GB", "Largest LOB KB", "Changes MB/h", "Excluded (no primary key)"], rows),
    )


def build(m: Migration, runbook_path) -> dict[str, str]:
    """Return {file name: content} for every evidence file this module produces."""
    rb = runbook.Runbook.load(runbook_path)
    return {
        "E-01-inventory.md": inventory(m),
        "E-02-classification.md": classification(m),
        "E-03-dependencies.md": dependencies(m),
        "E-04-sizing.md": sizing(m),
        "E-05-dms-coverage.md": dms_coverage(m),
        "E-06-plan-checks.txt": render(plan.run(m)),
        "E-07-runbook-checks.txt": render(runbook.run(rb, m)),
    }
